const FETCH_REQUEST_LOADING = "FETCH_REQUEST_LOADING"
const FETCH_REQUEST_SUCCESS = "FETCH_REQUEST_SUCCESS"
const FETCH_REQUEST_FAILURE = "FETCH_REQUEST_FAILURE"

export { FETCH_REQUEST_FAILURE, FETCH_REQUEST_SUCCESS, FETCH_REQUEST_LOADING}